<?php

/**
 * @file
 * Contains dung_beetle_sightings.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function dung_beetle_sightings_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the dung_beetle_sightings module.
    case 'help.page.dung_beetle_sightings':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Dung beetle sightings module') . '</p>';
      return $output;

    default:
  }
}
