<?php

/**
 * @file
 * Contains dung_beetle_sightings_migration.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function dung_beetle_sightings_migration_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the dung_beetle_sightings_migration module.
    case 'help.page.dung_beetle_sightings_migration':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Dung Beetle Migration Migration Module imports sightings into the sightings entity from the Atlas of Living Australia') . '</p>';
      return $output;

    default:
  }
}
